Repository kivy/python-for-android, pull requests merged in 2019-08, with the labels that each got.

#1937 Call Cython via `python -m Cython` rather than system-wide binary
  Dockerfile.py2
  Dockerfile.py3
  pythonforandroid/build.py
  pythonforandroid/recipe.py
  tests/test_toolchain.py
Labels: bug, need-testing

#1951 Fix build for case-insensitive FS and add CI test for OSX
  .travis.yml
  Dockerfile.py2
  Dockerfile.py3
  ci/makefiles/android.mk
  ci/makefiles/osx.mk
  pythonforandroid/python.py
  pythonforandroid/recipe.py
  pythonforandroid/recipes/python2/__init__.py
  pythonforandroid/recipes/python2/patches/fix-interpreter-version.patch
Labels: bug, need-testing, platform-osx

#1722 Initial migration to NDK r19 (Part I - The core)
  README.md
  ci/makefiles/android.mk
  doc/source/quickstart.rst
  pythonforandroid/archs.py
  pythonforandroid/python.py
  pythonforandroid/recipe.py
  pythonforandroid/recipes/jpeg/__init__.py
  pythonforandroid/recipes/libffi/__init__.py
  pythonforandroid/recipes/libffi/fix-includedir.patch
  pythonforandroid/recipes/libffi/remove-version-info.patch
  pythonforandroid/recipes/numpy/__init__.py
  pythonforandroid/recipes/numpy/patches/ar.patch
  pythonforandroid/recipes/numpy/patches/do_not_use_system_libs.patch
  pythonforandroid/recipes/numpy/patches/fix_environment_detection.patch
  pythonforandroid/recipes/numpy/patches/fix_setup_dependencies.patch
  pythonforandroid/recipes/openssl/__init__.py
  pythonforandroid/recipes/png/__init__.py
  pythonforandroid/recipes/pycrypto/__init__.py
  pythonforandroid/recipes/python2/__init__.py
  pythonforandroid/recipes/python2/patches/fix-missing-extensions.patch
  pythonforandroid/recipes/python2/patches/fix-zlib-version.patch
  pythonforandroid/recipes/python3/__init__.py
  pythonforandroid/recipes/python3/patches/fix-zlib-version.patch
  pythonforandroid/recommendations.py
  tests/test_archs.py
  tests/test_bootstrap.py
Labels: ndk-r19+

#1965 Remove `--sysroot` from LDFLAGS for cffi and pymunk
  pythonforandroid/recipes/cffi/__init__.py
  pythonforandroid/recipes/pymunk/__init__.py
Labels: bug, ndk-r19+

#1947 [LIBS - PART II] Part II of NDK r19 migration - Initial STL lib migration
  ci/constants.py
  pythonforandroid/recipe.py
  pythonforandroid/recipes/icu/__init__.py
  pythonforandroid/recipes/icu/disable-libs-version.patch
  pythonforandroid/recipes/pyicu/__init__.py
  pythonforandroid/recipes/pyicu/icu.patch
  tests/recipes/test_icu.py
  tests/recipes/test_pyicu.py
  tests/test_recipe.py
Labels: ndk-r19+

#1966 [WIP][LIBS - PART III] Rework of pyleveldb, leveldb and snappy
  pythonforandroid/recipes/leveldb/__init__.py
  pythonforandroid/recipes/leveldb/disable-so-version.patch
  pythonforandroid/recipes/leveldb/find-snappy.patch
  pythonforandroid/recipes/pyleveldb/__init__.py
  pythonforandroid/recipes/pyleveldb/bindings-only.patch
  pythonforandroid/recipes/snappy/__init__.py
Labels: ndk-r19+

#1967 [WIP][LIBS - PART IV] Rework of shapely and libgeos
  pythonforandroid/recipes/libgeos/__init__.py
  pythonforandroid/recipes/shapely/__init__.py
  pythonforandroid/recipes/shapely/setup.patch
Labels: ndk-r19+

#1968 [WIP][LIBS - PART V] Rework of libzmq
  pythonforandroid/recipes/libzmq/__init__.py
Labels: ndk-r19+

#1971 [WIP][LIBS - PART VII] Rework of libtorrent and boost
  pythonforandroid/recipes/boost/__init__.py
  pythonforandroid/recipes/boost/fix-android-issues.patch
  pythonforandroid/recipes/boost/user-config.jam
  pythonforandroid/recipes/libtorrent/__init__.py
  pythonforandroid/recipes/libtorrent/setup-lib-name.patch
Labels: ndk-r19+

#1936 Also copy the service/main.py when building with setup.py
  pythonforandroid/bootstraps/common/build/build.py
Labels: bug

#1969 [WIP][LIBS - PART VI] Rework of protobuf_cpp
  ci/constants.py
  pythonforandroid/recipes/protobuf_cpp/__init__.py
Labels: ndk-r19+
