Repository kivy/python-for-android, pull requests merged in 2019-06, with the labels that each got.

#1822 Added a matplotlib recipe
  pythonforandroid/bootstraps/sdl2/build/src/main/java/org/kivy/android/PythonUtil.java
  pythonforandroid/recipes/Pillow/__init__.py
  pythonforandroid/recipes/matplotlib/__init__.py
  pythonforandroid/recipes/matplotlib/mpl_android_fixes.patch
  pythonforandroid/recipes/matplotlib/setup.cfg.template
  pythonforandroid/recipes/pil/__init__.py
  pythonforandroid/recipes/pil/disable-tk.patch
  pythonforandroid/recipes/pil/fix-directories.patch
  pythonforandroid/recipes/png/__init__.py
  pythonforandroid/recipes/png/build_shared_library.patch
  pythonforandroid/recipes/six/__init__.py
  testapps/setup_testapp_python3_matplotlib.py
  testapps/testapp_matplotlib/main.py
Labels: WIP

#1839 Release 2019.06.06
  README.md
  ci/rebuild_updated_recipes.py
  doc/source/contribute.rst
  pythonforandroid/__init__.py
  setup.py
Labels: WIP

#1852 pythonpackage can't return build requirements for wheels, make it return an error if attempted
  pythonforandroid/pythonpackage.py
  tests/test_pythonpackage_basic.py
Labels: Priority: Critical, bug

#1857 Add `--without-bzip2` to freetype's configure args
  pythonforandroid/recipes/freetype/__init__.py
Labels: bug

#1856 Fix locating system python when it's not in $PATH (weird but happens, apparently)
  pythonforandroid/pythonpackage.py
Labels: Priority: High, WIP

#1855 Add unittest for `pythonforandroid.util` and...
  .travis.yml
  pythonforandroid/util.py
  tests/test_archs.py
  tests/test_distribution.py
  tests/test_util.py
Labels: Priority: Medium

#1862 Fix various setup.py processing bugs
  pythonforandroid/build.py
  pythonforandroid/pythonpackage.py
  pythonforandroid/toolchain.py
  tests/test_pythonpackage_basic.py
Labels: bug

#1871 Fix wrong env variable for `hostpython build path` in `archs.py`
  pythonforandroid/archs.py
Labels: bug

#1880 Typo
  pythonforandroid/recipes/android/src/android/permissions.py
Labels: bug

#1898 Fix `run_pymodules_install` when `project_dir` isn't supplied
  pythonforandroid/build.py
Labels: bug
